### ISSUE TITLE
Add ember version:bump command

### ISSUE THREAD

**Issue by taras** [EmberSherpa/ember-cli-app-version#15]
I'm thinking about adding `ember version:bump` command. I'm thinking about using [semver](https://github.com/npm/node-semver) library to increment version number by parameter. 

## Examples

* `ember version:bump major` - major version bump
* `ember version:bump minor` - minor version bump
* `ember version:bump patch` - patch version bump 

Before, I do this, I have a few questions:

1. Would you use it? 
2. Are you using something now and what?

**Comment by miguelcobain** [comment]
Is this basically a wrapper of `npm version`? 
That's what I'm using.

**Comment by taras** [comment]
@miguelcobain I didn't know about this command but yes. I was thinking about eventually adding *pre* and *post* hooks that could be used to execute *ember test* & *npm publish*.

**Comment by zeppelin** [comment]
@taras I'm using [grunt-bump](https://github.com/vojtajina/grunt-bump) right now, but I would be happy to have something similar as an ember-addon. Pre/post hooks sound like good additions.

**Comment by taras** [comment]
`ember release` does this.
