### ISSUE TITLE
Incorrect upgrade to ember-cli 0.2.0.

### ISSUE THREAD

**Issue by rwjblue** [embersherpa/ember-cli-app-version#17]
The custom `config` hook in `index.js` was removed by https://github.com/embersherpa/ember-cli-app-version/commit/e30885b0dc72eacb045ca93e85e0d7b5759b72ec, I am not sure how this library can be working at the moment...

**Comment by rwjblue** [comment]
@taras pin

**Comment by rwjblue** [comment]
@taras - Ping?

**Comment by taras** [comment]
Sorry, dropped the ball on this one. I'm looking at it now.

**Comment by rwjblue** [comment]
No worries!  TOO MANY NOTIFICATIONS!!!!
