### ISSUE TITLE
Access Version outside Templates

### ISSUE THREAD

**Issue by eatpurely** [EmberSherpa/ember-cli-app-version#33]
Feature request. Allow access to the app-version within controllers, components, etc.

Thanks in advance!

**Comment by taras** [comment]
You can do this today by importing the config into your controller or component. 

```js
import config from '../config/environment';

export default Ember.Component.extend({
  appVersion: config.APP.version
});
```

**Comment by eatpurely** [comment]
Thank you so much.

**Comment by Techn1x** [comment]
Useful, but it would be nice not to have to re-write the same code that's in the helper to get the version in the same format

Currently I'm doing this;
```javascript
import config from '../config/environment';
import { versionRegExp, versionExtendedRegExp } from 'ember-cli-app-version/utils/regexp';

export default Ember.Component.extend({
  appVersion: config.APP.version,
  appVersionFormatted: computed('appVersion', function(ver) {
    let match = ver.match(versionExtendedRegExp);	// 1.3.0-alpha.1
    if(!match) match = ver.match(versionRegExp);	// 1.3.0
    return match.toString();
    // return appVersionHelper([],{versionOnly: true, showExtended: true});
  }),
});
```

Whereas ideally I could just use that commented out line above that uses the imported helper `appVersionHelper`.

Other addons let you import helpers in the following way, but it doesn't seem to work for this addon
`import { round } from 'ember-math-helpers/helpers/round';`
