### ISSUE TITLE
Release v3.0.0 with Babel 6 Support

### ISSUE THREAD

**Issue by rwjblue** [EmberSherpa/ember-cli-app-version#40]
Could y'all release v3.0.0 from master (which includes https://github.com/EmberSherpa/ember-cli-app-version/pull/39).  

Note: it needs to be 3.0.0 because of dropping node@0.12 compat.

**Comment by taras** [comment]
Hey Robert, sorry for not pinging you. I published it earlier today. It should be up now. Please confirm.

**Comment by rwjblue** [comment]
The commits are not pushed to master (but the tag was pushed), so I just missed it.  Sorry about that!
