### ISSUE TITLE
Needs release of 3.1.0

### ISSUE THREAD

**Issue by rwjblue** [EmberSherpa/ember-cli-app-version#46]
The recent blueprint updates and version bumps that are on master need to be released (to go along with ember-cli@2.16.0-beta.1).  Can we get a 3.1.0 released?

Since this is included in ember-cli by default I wonder if you would mind allowing @stefanpenner or myself to publish/release also (I believe we have merge access but not `npm publish` access)?

/cc @taras @alexlafroscia

**Comment by alexlafroscia** [comment]
I don't have release access, only @taras does :( 

I think we should move this to the `ember-cli` org, probably.

**Comment by alexlafroscia** [comment]
Actually, I _can_ release, and will do so.

I still think we should move this to the `ember-cli` org, though.

**Comment by alexlafroscia** [comment]
I have publish access on the NPM package, but _not_ push access to master here...

So I published the NPM package, just can't update this, too

**Comment by alexlafroscia** [comment]
@rwjblue and @stefanpenner: I added you both as collaborators, so you can push versions now too

**Comment by rwjblue** [comment]
@alexlafroscia - Thank you!
