### ISSUE TITLE
sha

### ISSUE THREAD

**Issue by florent-blanvillain** [embersherpa/ember-cli-app-version#5]
Could you elaborate on how you obtain a sha at the end of the version number ? I imagine it's obvious but...

**Comment by taras** [comment]
This addon uses [git-repo-version](https://github.com/cibernox/git-repo-version/blob/master/index.js#L11) library which appends first 8 characters from git SHA to the version number in package.json. You can tell it to not add but SHA by adding + to the end of the version number.

- 1.1.1.2fd42c31
- 1.1.1+beta1 (+ causes it to not append the sha)

(1.1.1 is taken from package.json)

**Comment by florent-blanvillain** [comment]
Thanks, however I can't get it to add the SHA.

* My project is under git
* I have ` "version": "1.0.0"` in my package.json
* I tried to add git-repo-version and even git-repo-info to my dependencies

I feel like I'm missing something here... Maybe it is because I'm under ember-cli 0.1.2 ?

**Comment by taras** [comment]
It looks like I was wrong. It works the opposite to how I described. If you add + to the end, then it will append .sha. So, if you set the package.json version to 1.0.1.beta, then it will become 1.0.1.beta.2fd42c31

I changed this code to accommodate a request and now I don't understand it's intended to be used.

**Comment by taras** [comment]
@cibernox why does git-repo-version only append a hash to a version that has + in it? Can you describe the workflow that git-repo-version was created for?

**Comment by cibernox** [comment]
@taras It was for ember.js / ED workflow. 
In fact, I basically extracted and splitted a bit of functionality that was present in some ember-related projects: https://github.com/emberjs/ember.js/blob/00d1be8c455ff32b7a3005baa88ee70c3a75105a/lib/calculate-version.js

In ember, only builds with `+canary` or `+beta` get a sha at the end. 
It might be a good idea add a parameter to force SHA addition and that defaults to true if the version has a `+` in the name.

**Comment by taras** [comment]
I'm not sure if a pattern that is used for Ember framework development is appropriate for Ember App development.

In a large app that I was working on, we were using tags to mark all versions, so 1.0.1 would be a tag and the version in package.json. Our versioning would then automatically add SHA to end when there were commits beyond the latest tag. So, you know you're on a commit that was created after 1.0.1 was tagged.

@cibernox @florent-blanvillain does the Ember framework versioning workflow work for apps? Is my suggested workflow better? what do you think?

**Comment by cibernox** [comment]
It makes sense to me. If this commit has a tag on it, that's its name. If not, recover the latest tag in history and add the SHA. 

I think that that workflow could work for both, ember and apps.

**Comment by taras** [comment]
@cibernox to make this possible, we'd need to modify [https://github.com/rwjblue/git-repo-info/blob/master/index.js](https://github.com/rwjblue/git-repo-info/blob/master/index.js) because it doesn't currently know anything about tags.

**Comment by cibernox** [comment]
Yes, the need to change that. 

I've found a case that is not covered by that workflow, at least in ember project. Right now, master is tagged with `1.11.beta.1`. The last tag is `1.10.beta4`. Which one wins? I assume that always the newest one.

**Comment by taras** [comment]
It would be whichever is in package.json, because "since tag" is calculated on commits since last tag. If that information is missing, it will just append the hash to version in package.json.

**Comment by cibernox** [comment]
In a nutshell:

A. Current commit is tagged

Use the tag. P.e `1.0.1`

B.  Current commit is not tagged
Go back in history to find the last tagged commit.
B1) There is a tag and is greater than the on in package.json: Use tag + SHA
B2) Otherwise (no tags was found or it's older than the one in package.json): Use the version in package.json + SHA

Right?

**Comment by taras** [comment]
B. Current commit is not tagged

Use the version in package.json + SHA

---
In essence, we're only adding the ability to match tags to commits. From code prospective, we'll need to replace `version.indexOf('+')` with `isCurrentCommitTagged()`

**Comment by cibernox** [comment]
I have work for this evening then :)

**Comment by cibernox** [comment]
@rwjblue I ping you just in case you have something to add here about if this approach will work for ember.js

**Comment by taras** [comment]
@cibernox awesome :)

**Comment by florent-blanvillain** [comment]
@taras @cibernox It would be just perfect for my usage :)

**Comment by rwjblue** [comment]
git-repo-info 1.0.3 has been released and now includes the tag for the current sha (if available).  Thanks @cibernox!

**Comment by cibernox** [comment]
Version 0.1.0 of git-repo-version released: https://www.npmjs.com/package/git-repo-version

**Comment by taras** [comment]
@rwjblue @cibernox you guys rock! version 0.3.0 released with tag support!
