### ISSUE TITLE
Tag detection fixes in git-repo-info / git-repo-version.

### ISSUE THREAD

**Issue by rwjblue** [embersherpa/ember-cli-app-version#9]
The initial tag support only checked `.git/refs/packed-refs`, which will only contain tags that have been packed via `git pack-refs` ([see here](https://www.kernel.org/pub/software/scm/git/docs/git-pack-refs.html)).

By default tags are stored in `.git/refs/tags/` with a separate file for each tag (contents is the SHA).

For underlying support, see: https://github.com/rwjblue/git-repo-info/pull/2

Submitted https://github.com/cibernox/git-repo-version/pull/4 to update locked version.  Once @cibernox merge's and releases we need to update `git-repo-version` here.

**Comment by cibernox** [comment]
Fixed with #10
